name: browser_detector
description: Dart browser detector library. Detects browser, engine and platform based on the user agent string. Safe to use with Flutter.
version: 0.0.1
repository: https://github.com/aicantar/browser_detector
issue_tracker: https://github.com/aicantar/browser_detector/issues

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  test: ^1.15.7